### ISSUE TITLE
Build in appcompat support for <5.0

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#83]
Currently don't have any <5.0 devices to test with (other than emulator) but I think that appcompat isn't fully integrated so the styles in `values-v21` won't apply.  Need to test.

**Comment by jasonkliu** [comment]
http://android-developers.blogspot.com/2014/10/appcompat-v21-material-design-for-pre.html

**Comment by jasonkliu** [comment]
Tried it out on a 4.4.4 device and it crashed on MainActivity:

  Caused by: java.lang.NullPointerException
            at edu.yalestc.yalepublic.MainActivity.onCreate(MainActivity.java:91)

at the line ` actionbar.setDisplayShowTitleEnabled(true); `.

(This is with the appcompat-v21 enabled, with the normal v18 compat it works fine).

**Comment by jasonkliu** [comment]
This is solved by the following:
`public class MainActivity extends ActionBarActivity {` using `ActionBarActivity` instead of `Activity`,
and `android.support.v7.app.ActionBar actionbar = getSupportActionBar();`. 

However, now the top bar does not retain the theme (stays with original black color), and does not show the about icon (instead shows a dropdown menu.

**Comment by mahirrana** [comment]
This is almost done in the branch app-compat. Most of the activities are now working with devices 4.0 or higher. My internship has ended so I did not have time to finish it. The only thing I didn't fix was the color of the athletics toggle. On 4.0 devices, the text is black in the action bar for the athletics toggle. There might also be some other stylistic changes that need to be fixed. I didn't have time to do extensive testing.

**Comment by jasonkliu** [comment]
related to #136 and #137 etc, should be working now.  Will reopen if there are more issues later.
